### PR TITLE
Dev -> Stage Sync (Sep. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/697 (@Gbarra9)
- https://github.com/episphere/connect/issues/631. Update daily reports page in Reports tab (@abhinavjonnada82)
- https://github.com/episphere/biospecimen/issues/564. Add Shipping Reports to BPTL (@abhinavjonnada82)
- https://github.com/episphere/biospecimen/issues/548 (@Gbarra9)
- https://github.com/episphere/connect/issues/708 (@JoeArmani, @Gbarra9)
- https://github.com/episphere/connect/issues/625 (@JoeArmani)
- https://github.com/episphere/connect/issues/693 (@abhinavjonnada82 & @Gbarra9)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]

**Comment by JoeArmani** [comment]
my updates have been tested in dev and approved.

**Comment by Gbarra9** [comment]
My updates have been tested in dev and ready for stage **except** "Add Orland Park location to shipping dashboard".

**Comment by abhinavjonnada82** [comment]
Looks good & can move forward!

**Comment by Gbarra9** [comment]
[Add New Locations for UChicago & Marshfield connect#693](https://github.com/episphere/connect/issues/693)

Last update has been tested in dev and ready for stage.

**Pull request merged**
